//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingredient
    {
        public int id { get; set; }
        public int userid { get; set; }
        public string text { get; set; }
        public decimal quantity { get; set; }
        public string measure { get; set; }
        public decimal weight { get; set; }
        public string food { get; set; }
    
        public virtual user user { get; set; }
    }
}
