//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipe
    {
        public int id { get; set; }
        public string uri { get; set; }
        public string label { get; set; }
        public string imageurl { get; set; }
        public string source { get; set; }
        public string url { get; set; }
        public string shareas { get; set; }
        public Nullable<decimal> yield { get; set; }
        public string dietlabel { get; set; }
        public string healthlabel { get; set; }
        public string caution { get; set; }
        public string ingredientlines { get; set; }
        public Nullable<decimal> calories { get; set; }
        public Nullable<decimal> totalweight { get; set; }
        public int userid { get; set; }
    
        public virtual user user { get; set; }
    }
}
