//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class virtualkitchendbEntities : DbContext
    {
        public virtualkitchendbEntities()
            : base("name=virtualkitchendbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<device> devices { get; set; }
        public virtual DbSet<ingredient> ingredients { get; set; }
        public virtual DbSet<my_recipes> my_recipes { get; set; }
        public virtual DbSet<recipe> recipes { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
